### ISSUE TITLE
Tasks List

### ISSUE THREAD

**Issue by shanksdev** [shanksdev/win10#6]
# Tasks List
1. [ ] Loading of login screen
  - [ ] Login screen time widget
  - [ ] Login screen fact widget
  - [ ] Login screen click to slide up and show pin/password field to login with demo user.
  - [ ] Login success redirect to home screen.
  - [ ] Login failure display error message.
2. [x] Home screen.
  - [ ] Selection of desktop icons.
  - [ ] Right click handling on desktop empty area.
  - [ ] Ability to change background by browsing the image.
  - [ ] Task bar icons click handling and animation.
3. [ ] Windows frame setup
  - [ ] Allow simulation of application such as settings along with capability to minimize and maximize.
  - [ ] Resizable windows if possible.
4. [ ] System Tray icons - 
  - [ ] Click event on system tray icons.
  - [ ] Hover state with animation.
  - [ ] Show current Date Time
  - [ ] Open calendar on Date Time click.
  - [ ] Notifications panel to be opened from notification button in system tray.
5. [ ] Notifications area - 
  - [ ] Shortcut to most common settings along with toggle state management using ngrx
6. [ ] Tablet View
  - [ ] Switch to tablet view on resizing the window or from shortcut button in right menu as mentioned in 5.1
  - [ ] Design components to handle tab view.
7. [ ] Task Bar
  - [ ] Handle windows button click to open start menu with list of apps.
  - [ ] Show settings, logout/lock option.
  - [ ] Start menu should open with same animation as windows.
  - [ ] [Optional] Create new and interests panel.
